spring:
  profiles:
    active: local
    include: oauth

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/nadeulseoul
    username: root
    password: root

  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true

  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 2
        max-idle: 2
        min-idle: 0

app:
  auth:
    tokenSecret:
    tokenExpirationMsec: 864000000
