spring:
  profiles:
    active: local
    include: oauth

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/nadeulseoul
    username: root
    password: root

  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 2
        max-idle: 2
        min-idle: 0

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  main:
    allow-bean-definition-overriding: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
app:
  auth:
    tokenSecret: nes0610ljy
    tokenExpirationMsec: 864000000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth/redirect

